### ISSUE TITLE
Error with gnome-shell 3.34

### ISSUE THREAD

**Issue by glitsj16** [BjoernDaase/noannoyance#1]
Hi, I've been using this extension for a while in its https://github.com/sindex/no-annoyance form. That still works on Arch Linux with gnome-shell 3.34. As your fork uses ES6 syntax I wanted to give it a try, I uninstalled the former, followed the build instructions and installed. But gnome-shell refuses to enable it and journalctl shows this error:

```
Sep 26 05:13:45 gnome-shell[1174]: JS ERROR: Extension noannoyance@daase.net: TypeError: window is undefined
                                         _onWindowDemandsAttention@/usr/share/gnome-shell/extensions/noannoyance@daase.net/extension.js:15:5
                                         StealMyFocus@/usr/share/gnome-shell/extensions/noannoyance@daase.net/extension.js:11:74
                                         enable@/usr/share/gnome-shell/extensions/noannoyance@daase.net/extension.js:30:18
```

Is this something that is reproducable?

**Comment by BjoernDaase** [comment]
@glitsj16 Thank you for taking the time reporting this issue :)

https://github.com/BjoernDaase/noannoyance/commit/4cd3ac05e548590f77050b91be96aa80c610d5b4 already landed in the initial commit, which was not supposed to. I reverted this change and pushed the new version to extensions.gnome.org.

We maybe have to wait one or two days for it to be accepted.

**Comment by BjoernDaase** [comment]
Anyway, with https://github.com/BjoernDaase/noannoyance/commit/02750982187e59765f3bc7264d019001181810d7 it is now fixed correctly.

**Comment by BjoernDaase** [comment]
And the new version is online on extensions.gnome.org

**Comment by glitsj16** [comment]
@BjoernDaase Just installed and it's working great now. Thanks for the speedy fix!
