### ISSUE TITLE
'Windows is ready' notification haven't gone completely

### ISSUE THREAD

**Issue by validatedev** [BjoernDaase/noannoyance#2]
I'm using Ubuntu 20.04 with GNOME 3.34.2. The extension works correctly but if I'm not wrong there isn't any notification has appeared on me like 'Windows is ready' when I used with the older GNOME version. There's a notification appears with a duration like half of a second or something and then focuses the window.

**Comment by BjoernDaase** [comment]
Thanks for talking time to report this issue :)
Interestingly, I do not see that behavior on Fedora 31, also with Gnome 3.34.2 (I mainly use it to silence the Geary 'Window is ready' notification).  
Could you please give me an example application where you see the behavior you describe?

**Comment by BjoernDaase** [comment]
Btw, thanks for giving me the hint with the typo, I hope 'Windows' is actually never ready for me :dancer:

**Comment by BjoernDaase** [comment]
Anyway, I have just fixed a bug that disabling and reenabling did not work properly: https://github.com/BjoernDaase/noannoyance/commit/4eed6d5c2276b1ab40378db0ac341ece9d02ce0c.  
Even though I can not really think of how that could be related, you could try out the newest version from GitHub :)

**Comment by validatedev** [comment]
Well, sorry for the delayed response. I've been very busy nowadays. It sometimes works as intended without any notification, sometimes it pops up a little box for "Window is ready" (lol), then focus the app. I'll try the latest version, but first I should do my other things that is causing my situation of busyness. BRB!

**Comment by validatedev** [comment]
Well, in five days, I haven't encountered any issue with the extension. It works what it should be. Closing.
