### ISSUE TITLE
Not getting focus from dual monitor

### ISSUE THREAD

**Issue by IvoryJam** [BjoernDaase/noannoyance#7]
When I have an application in focus on monitor 1, I move my mouse to monitor 2 and use "ctrl-alt-T" to open the terminal, the extension doesn't focus the new terminal on monitor 2

I'm using the current version of "NoAnnoyance v2" on https://extensions.gnome.org/extension/2182/noannoyance/

Ubuntu 19.10
Kernel 5.3.0-46-generic

**Comment by BjoernDaase** [comment]
Hey,
Thanks for taking time to report this. But I do not fully understand the problem yet.  

Therefore, could you please elaborate a bit more (including clear steps to reproduce, current and expected behaviour) what the issue is? Maybe including a screencast might help as well?

**Comment by IvoryJam** [comment]
Sure can! I have two monitors, let's call them monitor_1 and monitor_2. I have Firefox open on monitor_1 and it's in focus. I drag my mouse cursor to monitor_2 and, while Firefox is still in focus on monitor_1, I type my command to open the terminal, "CTRL-ALT-T". 

With Firefox open on monitor_1 and using "CTRL-ALT-T" to open the terminal on monitor_1, it does steal focus and everything is okay.

Expected: new terminal on monitor_2 should steal focus from Firefox on monitor_1

Current: Firefox on monitor_1 maintains focus even after the terminal has been opened on monitor_2

**Comment by BjoernDaase** [comment]
Alright, I think I get your problem now, thanks :+1: 

Besides the fact that I can not reproduce this behaviour on Fedora 32 with Gnome-shell 3.36.1 (I exactly followed your steps and my new terminal on monitor_2 got focused as expected) what you describe is not in the scope of this extension: This extension is only about the `Window is ready` notification which sometimes appears when clicking on notifications.

Anyway, you might want to play around with the window focus mode (editable via gnome-tweaks) and see whether this fixes your issues. If that also does not help you might want to report this issue against gnome-shell as the behaviour you describe definitely does not sound correct.

**Comment by IvoryJam** [comment]
Leaving here in case anyone comes across the issue again, it was xfce4-terminal causing it, switched to tilix and issue is longer there.
